### ISSUE TITLE
Injection regex highlighting

### ISSUE THREAD

**Issue by dbernheisel** [ananthakumaran/tree-sitter-elixir#23]
Is there a way to identify the sigil symbol, such as `r` in `~r/foo/`, to allow for an injected treesitter language to be used?

Currently, this is how treesitter sees a regex:

![image](https://user-images.githubusercontent.com/643967/120140221-0eafc980-c1a8-11eb-915b-18078cd5c6b0.png)

**Comment by ananthakumaran** [comment]
![image](https://user-images.githubusercontent.com/149238/120144404-72191600-c1ff-11eb-926a-304f631aa483.png)

yes, you can try to match `sigil_start` value . https://ananthakumaran.in/tree-sitter-elixir/ is currently broken because of https://github.com/tree-sitter/tree-sitter/issues/1098. I haven't pinned the emcc version, you can test these in your local machine using `make ui` with correct emcc version.

**Comment by dbernheisel** [comment]
@ananthakumaran thanks! This approach would require matching on every opening character (SIGIL_CHARS in scanner.cc). It looks like `#match?` [might accept a regex](https://tree-sitter.github.io/tree-sitter/using-parsers) so it could have all sigil chars in there and work!

My end-goal is to include injections to specify markdown for heredoc, regex for R sigils, and inform other parsers about embedded Elixir in having the main content be html with elixir injected.  I see [tree-sitter-embedded-template](https://github.com/tree-sitter/tree-sitter-embedded-template) but can't find how it's used anywhere; it currently specifies ERB and EJS.

**Comment by dbernheisel** [comment]
Thank you for the help. I ended up contributing this to nvim-treesitter

https://github.com/nvim-treesitter/nvim-treesitter/pull/1353
